In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("../dataset/Indian_healthcare.csv")
df.head()

,Patient_ID,Age,Gender,Region,Socioeconomic_Status,Occupation,Visit_Date,Symptoms,Primary_Diagnosis,Blood_Glucose_mg_dL,HbA1c_%,Total_Cholesterol_mg_dL,Treatment_Type,Treatment_Outcome,Imaging_Type,Imaging_Findings,Hospital_Type,Insurance_Covered,BMI
0,21D74F65-E20,53,Female,Andhra Pradesh,Low,Clinical research associate,2025-09-18,"Fever, fatigue, increased thirst",Dengue,100.9,5.9,233.4,Lifestyle Changes,Improved,Ultrasound,Evidence of pleural effusion,Government,False,23.3
1,0BCF80B5-312,36,Male,Puducherry,Low,Agricultural consultant,2024-11-14,"Swelling in legs, high BP",Malaria,121.3,2.5,231.1,Medication,Referred,NaN,No imaging performed,Private,True,26.9
2,5EF60C7B-8E6,28,Male,Maharashtra,Low,Haematologist,2026-02-20,"Fever, fatigue, increased thirst",Hypertension,74.7,8.6,260.8,Lifestyle Changes,Improved,NaN,No imaging performed,Private,True,29.1
3,93959ACB-8BA,34,Female,Karnataka,Low,Financial risk analyst,2025-11-04,"Fever, fatigue, increased thirst",Cardiovascular Disease,102.7,5.2,244.8,Antibiotics,Referred,CT Scan,No significant abnormality detected,Government,False,26.4
4,B11DB540-128,48,Female,Puducherry,High,Environmental health practitioner,2025-08-15,"Frequent urination, blurred vision",Hypertension,61.0,6.0,280.3,Combination Therapy,Recovered,MRI,No significant abnormality detected,Government,True,33.1

In [9]:
df.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [14]:
df.shape

(1338, 7)

In [13]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [11]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [10]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010